name: helloworld
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  helloworld:
    runs-on: f1vossut001
    #container: hashicorp/terraform:1.0.3 # dockerhub等から任意のコンテナイメージを選べる
    steps:
      - run: |
          uname -a
          hostname
          users


