name: helloworld
on:
  push:
    branches: [ checkout ]
  pull_request:
    branches: [ checkout ]
  workflow_dispatch:
jobs:
  helloworld:
    runs-on: ubuntu-22.04 # 他にWindowsやMacOSが選べる
    container: hashicorp/terraform:1.0.3 # dockerhub等から任意のコンテナイメージを選べる
    steps:
      - uses: actions/checkout@v2
      - run: |
          uname -a
          cd files
          cat text.txt
          

