name: helloworld
on:
  push:
    branches: [ on_necci ]
  pull_request:
    branches: [ on_necci ]
  workflow_dispatch:
jobs:
  helloworld:
    runs-on: [self-hosted, necci]
    steps:
      - run: |
          uname -a
          echo Hello, world!

