name: helloworld
on:
  push:
    branches: [ checkout ]
  pull_request:
    branches: [ checkout ]
  workflow_dispatch:
jobs:
  helloworld:
    runs-on: [self-hosted, necci2]
    container: hashicorp/terraform:1.0.3
    steps:
      - uses: actions/checkout@v2
      - run: |
          uname -a
          cd files
          cat text.txt
          

