name: helloworld
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  helloworld:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          uname -a
          echo Hello, world!

